seqeralabs/tower-cli

src/main/java/io/seqera/tower/cli/commands/pipelines/ImportCmd.java
src/test/java/io/seqera/tower/cli/pipelines/PipelinesCmdTest.java
src/test/resources/runcmd/pipelines_add_no_workdir.json

Following same `pipelines add` behaviour, at `pipelines import` parameters that can be platform dependent (`workDir`, `preRunScript`, `postRunScript`) are inherited from the compute environment when they are not provided.

Platform dependent pipeline import parameters

---

README.md
src/main/java/io/seqera/tower/cli/commands/LaunchCmd.java
src/main/java/io/seqera/tower/cli/commands/actions/UpdateCmd.java
src/main/java/io/seqera/tower/cli/commands/actions/add/AbstractAddCmd.java
src/main/java/io/seqera/tower/cli/commands/pipelines/AddCmd.java
src/main/java/io/seqera/tower/cli/commands/pipelines/LaunchOptions.java
src/main/java/io/seqera/tower/cli/commands/pipelines/UpdateCmd.java
src/main/java/io/seqera/tower/cli/commands/runs/RelaunchCmd.java
src/test/java/io/seqera/tower/cli/pipelines/PipelinesCmdTest.java

In general, when it is possible, we tend to use same options that `nextflow run` is using.
- Use always `--profile` instead of `--profiles`. Resolves #160 
- Use `--params-file` instead of only `--params`. This is what Nextflow is using and also when we've single parameters (see #89) will make more sense to distinguish the parameters that you pass from a file and the ones that you pass as a command option.

Consistently name comand line options

---

.github/workflows/build.yml
build.gradle
src/main/java/io/seqera/tower/cli/commands/AbstractApiCmd.java
src/main/java/io/seqera/tower/cli/commands/InfoCmd.java

Define the HTTP agent header as:
```
User-Agent: tw/<cli version> (<platform>)
```
For platform I mean the same suffix that we add at the release assets: `linux-x86_64`, `osx-x86_64` and `windows-x86_64`.
Example:
```
User-Agent: tw/0.5.1 (linux-x86_64)
```
Fixes #192 
Check the different platform binaries with this command:
```
tw -v info
```
It should show the new `User-Agent` header at the HTTP request logs.

Customize HTTP agent header

---

src/main/java/io/seqera/tower/cli/commands/datasets/AddCmd.java
src/test/java/io/seqera/tower/cli/datasets/DatasetsCmdTest.java

Adds a validation check at command `tw datasets add ... <dataset_file_path>` to verify that the file exists before creating the dataset request. Fixes #187

Check that dataset path file exists

---

src/main/java/io/seqera/tower/cli/commands/AbstractApiCmd.java
src/main/java/io/seqera/tower/cli/exceptions/InvalidWorkspaceParameterException.java

Bad usage examples that now give a better error message:
```
tw compute-envs list --workspace "my_org /"
```
```
tw compute-envs list --workspace missing_org
```
And now it's trimming blank spaces so:
```
tw compute-envs list --workspace " my_org / my_wsp "
```
is valid like the equivalent:
```
tw compute-envs list --workspace my_org/my_wsp
```
Fixes #182

Improve error message for invalid workspace ids

---

src/main/java/io/seqera/tower/cli/commands/LaunchCmd.java
src/test/java/io/seqera/tower/cli/LaunchCmdTest.java

Allow to set the run name at `tw launch --name <custom_name> ... `
Fixes #200 and #150
Launch a pipeline using the flag `-n / --name`.

Add custom run name

---

src/main/java/io/seqera/tower/cli/commands/global/PaginationOptions.java
src/test/java/io/seqera/tower/cli/members/MembersCmdTest.java
src/test/java/io/seqera/tower/cli/participants/ParticipantsCmdTest.java
src/test/java/io/seqera/tower/cli/pipelines/PipelinesCmdTest.java
src/test/java/io/seqera/tower/cli/runs/RunsCmdTest.java
src/test/java/io/seqera/tower/cli/teams/TeamsCmdTest.java

Removing the option `--no-max` because it is not working as expected. The API cannot return all the elements of a list, so we need to implement pagination multi requests at CLI side. Related issue #220

Remove --no-max pagination option

---

.github/workflows/build.yml

No need to explicitly skip the actions on `[skip ci]` because it is the default github behaviour.
https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

Remove uneeded github action if 

---

.github/workflows/build.yml
build.gradle
jreleaser.yml

- Rollback to use MUSL to build the static linked binary. This proof to be the version that works for most of the users, except some that use a very old GLibc version.
- Add a new Tower CLI distribution that is a pure Java JAR, for users that experience problems with the MUSL static linked version. This distribution has to be use like `java -jar tw.jar ...` . Example `java -jar tw.jar info`

Rollback to MUSL as static linked version and add JAR distribution

---

src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/AwsBatchForgePlatform.java

Fixes #261. 
This change introduce the support for `executionRole` API parameter when creating a new forge aws-batch environment

Add support for batch execution role

---

README.md

A user should do one of these, but not both of them. Use a list instead of an enumeration.

Clarify ways to specify an access token

---

.github/workflows/build.yml
.sdkmanrc
build.gradle

Update GH Actions file, build.gradle and .sdkmanrc to use Java 17 runtime.

Upgrade GH Actions and gradle build to use Java 17 runtime

---

src/main/java/io/seqera/tower/cli/responses/InfoResponse.java

Simple health check status message rename from UNDEFINED to SKIPPED.
Closes #248
Health check against a non-existent API URL `tw -u https://localhost:9999 info`:
Detail fields that cannot be retrieved stay as UNDEFINED and the skipped health checks show as SKIPPED.

Improve log statuses for health checks

---

.github/workflows/build.yml
jreleaser.yml

This PR will add the release job to publish tower-cli to homebrew
1. add jreleaser PAT to build.yml
2. add brew packager to jreleaser.yml

Release job to publish tower-cli to homebrew

---

.github/workflows/build.yml

mac-12 will be removed in November 2024, so updating it to latest
https://github.com/actions/runner-images/issues/10721

updated mac runner for intel

---

build.gradle
conf/reflect-config.json
src/main/java/io/seqera/tower/cli/commands/DataStudiosCmd.java
src/main/java/io/seqera/tower/cli/commands/datastudios/AbstractStudiosCmd.java
src/main/java/io/seqera/tower/cli/commands/datastudios/DataStudioConfigurationOptions.java
src/main/java/io/seqera/tower/cli/commands/datastudios/StartCmd.java
src/main/java/io/seqera/tower/cli/responses/datastudios/DataStudioStartSubmitted.java
src/main/java/io/seqera/tower/cli/utils/ResponseHelper.java
src/test/java/io/seqera/tower/cli/datastudios/DataStudiosCmdTest.java
src/test/resources/runcmd/datastudios/datastudios_start_response.json
src/test/resources/runcmd/datastudios/datastudios_view_response_studio_starting.json
src/test/resources/runcmd/datastudios/datastudios_view_response_studio_stopped.json

Work relates to task: https://seqera.atlassian.net/browse/PLAT-1242
Summary: add the ability to start a data studio via the CLI.
Optionality to:
* override/update any of the existing DataStudio configurations (gpu, cpu, mountData, etc.) or description
* have command wait for specific status of DataStudio
**Trigger a start (default asyncrounous command):**
```
$ ./tw studios start -w 27230932650799 -i 6c74268d
Data Studio 6c74268d START successfully submitted at [data-studios / data-studios] workspace.
https://dev-tower.net/orgs/data-studios/workspaces/data-studios/studios/6c74268d/connect
```
https://github.com/user-attachments/assets/7226c2ff-7e16-4645-a81e-5243ffd66a37
**Trigger a start with override configuration supplied**
```
$ ./tw studios start -w 27230932650799 -i 6c74268d …
```

PLAT-1242 - Add DataStudio start command.

---

conf/reflect-config.json
src/main/java/io/seqera/tower/cli/commands/DataStudiosCmd.java
src/main/java/io/seqera/tower/cli/commands/datastudios/CheckpointsCmd.java
src/main/java/io/seqera/tower/cli/responses/datastudios/DataStudioCheckpointsList.java
src/main/java/io/seqera/tower/cli/responses/datastudios/DataStudiosView.java
src/test/java/io/seqera/tower/cli/datastudios/DataStudiosCmdTest.java
src/test/resources/runcmd/datastudios/datastudios_checkpoints_list_response.json

Relates to: https://seqera.atlassian.net/browse/PLAT-1418
```
$ ./tw studios checkpoints -w data-studios/data-studios -n studio-ef6b
Checkpoints at data studio studio-ef6b at [data-studios / data-studios] workspace:
ID  | Name                   | Author         | Date Created                  | Date Saved
-----+------------------------+----------------+-------------------------------+-------------------------------
158 | studio-ef6b_1737635204 | georgi-hristov | Thu, 23 Jan 2025 12:26:44 GMT | Thu, 23 Jan 2025 12:31:48 GMT
159 | studio-ef6b_1737635574 | georgi-hristov | Thu, 23 Jan 2025 12:32:54 GMT | Thu, 23 Jan 2025 12:38:07 GMT
160 | studio-ef6b_1737636023 | georgi-hristov | Thu, 23 Jan 2025 12:40:23 GMT | Thu, 23 Jan 2025 12:44:01 GMT
161 | studio-ef6b_1737636325 | georgi-hristov | …
```

PLAT-1418 - Add command to retrieve data studio checkpoints

---

conf/reflect-config.json
src/main/java/io/seqera/tower/cli/commands/data/links/DataLinkService.java
src/main/java/io/seqera/tower/cli/commands/datastudios/DataLinkRefOptions.java
src/main/java/io/seqera/tower/cli/responses/datastudios/DataStudioStartSubmitted.java
src/main/java/io/seqera/tower/cli/responses/datastudios/DataStudiosCreated.java
src/test/java/io/seqera/tower/cli/datastudios/DataStudiosCmdTest.java

Relates to : https://seqera.atlassian.net/browse/PLAT-1418
A known bug in the picocli framework causes even optional params that are grouped together to appear as mandatory in the --help section (as denoted by the `*`).
This causes the options to mount data to appear as mandatory, while they are optional.
```
Usage: tw studios start [OPTIONS]
Start a data studio.
Options:
-w, --workspace=<workspace>       Workspace numeric identifier (TOWER_WORKSPACE_ID as default) or workspace reference as OrganizationName/WorkspaceName
* -i, --id=<sessionId>              DataStudio session ID.
* -n, --name=<dataStudioName>       DataStudio name.
*     --mount-data=<mountDataNames>[,<mountDataNames>...]
Optional configuration override for 'mountData' setting (comma separate list of data-link names)
* …
```

PLAT-1418 - Workaround fix for mount-data options showing as mandatry in the --help, while they are optional

---

src/main/java/io/seqera/tower/cli/commands/datastudios/AddCmd.java
src/main/java/io/seqera/tower/cli/commands/datastudios/CheckpointsCmd.java
src/main/java/io/seqera/tower/cli/commands/datastudios/DataLinkRefOptions.java
src/main/java/io/seqera/tower/cli/commands/datastudios/DataStudioConfigurationOptions.java
src/main/java/io/seqera/tower/cli/commands/datastudios/DataStudioRefOptions.java
src/main/java/io/seqera/tower/cli/commands/datastudios/DataStudioTemplateOptions.java
src/main/java/io/seqera/tower/cli/commands/datastudios/DeleteCmd.java
src/main/java/io/seqera/tower/cli/commands/datastudios/ListCmd.java
src/main/java/io/seqera/tower/cli/commands/datastudios/ParentDataStudioRefOptions.java
src/main/java/io/seqera/tower/cli/commands/datastudios/StartAsNewCmd.java
src/main/java/io/seqera/tower/cli/commands/datastudios/StartCmd.java
src/main/java/io/seqera/tower/cli/commands/datastudios/StopCmd.java
src/main/java/io/seqera/tower/cli/commands/datastudios/TemplatesCmd.java
src/main/java/io/seqera/tower/cli/commands/datastudios/ViewCmd.java
src/main/java/io/seqera/tower/cli/responses/datastudios/DataStudioCheckpointsList.java
src/main/java/io/seqera/tower/cli/responses/datastudios/DataStudioDeleted.java
src/main/java/io/seqera/tower/cli/responses/datastudios/DataStudioStartSubmitted.java
src/main/java/io/seqera/tower/cli/responses/datastudios/DataStudioStopSubmitted.java
src/main/java/io/seqera/tower/cli/responses/datastudios/DataStudiosCreated.java
src/main/java/io/seqera/tower/cli/responses/datastudios/DataStudiosList.java
src/main/java/io/seqera/tower/cli/responses/datastudios/DataStudiosTemplatesList.java
src/main/java/io/seqera/tower/cli/responses/datastudios/DataStudiosView.java

Small fixes post verification of: https://seqera.atlassian.net/browse/PLAT-583
Fix sort of the `tw studio checkpoints` command (the list is already sorted from the backend, so just using the given sort instead of doing any sorting on the cli side, which is slightly broken).
```
/tw studios checkpoints -w data-studios/data-studios -n studio-ef6b
Checkpoints at Studio studio-ef6b at [data-studios / data-studios] workspace:
ID  | Name                   | Author         | Date Created                  | Date Saved
-----+------------------------+----------------+-------------------------------+-------------------------------
333 | studio-ef6b_1738341636 | georgi-hristov | Fri, 31 Jan 2025 16:40:36 GMT | Fri, 31 Jan 2025 17:59:29 GMT
195 | studio-ef6b_1738229371 | georgi-hristov | Thu, 30 Jan …
```

Rename "Data studios" to "studios" + other small readability standarisation

---

src/main/java/io/seqera/tower/cli/responses/studios/StudiosList.java
src/main/java/io/seqera/tower/cli/responses/studios/StudiosView.java
src/main/java/io/seqera/tower/cli/utils/FormatHelper.java

Noticed while doing some testing that for Studios where the description had a line break or was too long, it resulted in the table output being formatted wrong - this PR sanitises the description a bit to avoid badly formatted output and improve readability.
Before:
```
./tw studios list -w data-studios/data-studios
Studios at [data-studios / data-studios] workspace:
ID       | Name                      | Description                                                              | User               | Status
----------+---------------------------+--------------------------------------------------------------------------+--------------------+-------------
abec0e2c | studio-c9f5               | test mount
Started from studio jboxman-test-012725b                     | jason-boxman       | …
```

Format the description of a studio to remove line breaks to increase readability

---

.github/workflows/build.yml

The following removes the use of the `GH_SEQERA_TOKEN` as it's not required for relevant build steps as artifacts originate from a public repository.

chore:(CI) Use Github action credentials vs service account.   

---

src/main/java/io/seqera/tower/cli/shared/ComputeEnvExportFormat.java

https://github.com/seqeralabs/tower-cli/issues/394 
Fixes the issue when creating a compute environemnt from a json file with the labels field

fix(labels-import): pass the type info to the mapper
