seqeralabs/tower-cli

- conf/reflect-config.json
- src/main/java/io/seqera/tower/cli/commands/workspaces/DeleteCmd.java
- src/main/java/io/seqera/tower/cli/commands/workspaces/UpdateCmd.java
- src/main/java/io/seqera/tower/cli/commands/workspaces/ViewCmd.java
- src/main/java/io/seqera/tower/cli/commands/workspaces/WorkspacesMatchOptions.java
Using an `@ArgGroup(multiplicity = "1")` to force the user choose between id or names to select a workspace.
Fixes #49
> Force to choose workspace using id or names

- README.md
https://seqera.slack.com/archives/G01GNJ63HLY/p1636642651189600
> Updates the CE creation command

- src/main/java/io/seqera/tower/cli/commands/AbstractApiCmd.java
- src/main/java/io/seqera/tower/cli/responses/HealthCheckResponse.java
- src/main/java/io/seqera/tower/cli/responses/Response.java
- src/test/java/io/seqera/tower/cli/HealthCheckCmdTest.java
- src/test/java/io/seqera/tower/cli/LaunchesCmdTest.java
- src/test/java/io/seqera/tower/cli/Pipelines/PipelinesCmdTest.java
- src/test/java/io/seqera/tower/cli/actions/ActionsCmdTest.java
- src/test/java/io/seqera/tower/cli/computeenvs/ComputeEnvsCmdTest.java
- src/test/java/io/seqera/tower/cli/credentials/CredentialsCmdTest.java
- src/test/java/io/seqera/tower/cli/credentials/providers/AwsProviderTest.java
- src/test/java/io/seqera/tower/cli/credentials/providers/GoogleProviderTest.java
- src/test/java/io/seqera/tower/cli/credentials/providers/SshProviderTest.java
- src/test/java/io/seqera/tower/cli/members/MembersCmdTest.java
- src/test/java/io/seqera/tower/cli/organizations/OrganizationsCmsTest.java
- src/test/java/io/seqera/tower/cli/participants/ParticipantsCmdTest.java
- src/test/java/io/seqera/tower/cli/runs/RunsCmdTest.java
- src/test/java/io/seqera/tower/cli/teams/TeamsCmdTest.java
- src/test/java/io/seqera/tower/cli/workspaces/WorkspacesCmdTest.java
- Use picocli exit codes. Resolves #95
> Normalize exit codes

- src/main/java/io/seqera/tower/cli/utils/ErrorReporting.java
- Show nice connection error. Resolves #21
> Improve error message

- src/main/java/io/seqera/tower/cli/Tower.java
- src/main/java/io/seqera/tower/cli/commands/AbstractApiCmd.java
- src/test/java/io/seqera/tower/cli/BaseCmdTest.java
- Block non HTTPS connection by default. Resolves #114
> Add 'insecure' option to allow to connect to HTTP

- src/main/java/io/seqera/tower/cli/commands/LaunchesCmd.java
- src/main/java/io/seqera/tower/cli/utils/ModelHelper.java
- src/test/java/io/seqera/tower/cli/LaunchesCmdTest.java
> Add the pipeline launch ID.

- conf/reflect-config.json
- src/main/java/io/seqera/tower/cli/Tower.java
- src/main/java/io/seqera/tower/cli/commands/LaunchCmd.java
- src/test/java/io/seqera/tower/cli/LaunchCmdTest.java
> Only allow full URL Nextflow pipelines at launch

- src/main/java/io/seqera/tower/cli/commands/pipelines/ImportCmd.java
> Do not allow null compute env ids at pipeline import

- src/main/java/io/seqera/tower/cli/commands/AbstractApiCmd.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/AbstractComputeEnvCmd.java
- src/test/java/io/seqera/tower/cli/computeenvs/ComputeEnvsCmdTest.java
- src/test/resources/runcmd/compute_env_view_aws_manual.json
> Allow view and delete any compute environment

- src/main/java/io/seqera/tower/cli/commands/LaunchCmd.java
- src/main/java/io/seqera/tower/cli/commands/pipelines/LaunchOptions.java
> Make config description more clear.

- .github/workflows/lint-markdown.yml
- src/main/java/io/seqera/tower/cli/commands/runs/ViewCmd.java
the command `tw runs view` fails with runs launched from Nextflow because there is no related compute environment.
Fixes #195
> Fix runs view for runs launched from NF cli

- conf/jni-config.json
- conf/reflect-config.json
- conf/resource-config.json
This are files automatically generated by GraalVM. It seems that the formatting style has slightly changed with the latest GraalVM version. This PR update the formatting.
> Update JSON config files to the format used by GraalVM v22

- src/main/java/io/seqera/tower/cli/Tower.java
- src/main/java/io/seqera/tower/cli/commands/InfoCmd.java
Two small changes
- Fix #194
- Feature #183
> Add TOWER_OUTPUT_FORMAT environment variable and fix error message

- USAGE.md
Follow up to https://github.com/seqeralabs/tower-cli/pull/231
Ping @abhi18av
> Review usage docs for Tower CLI

- .github/workflows/rich-codex-screenshot.yml
- USAGE.md
- assets/img/rich_codex/tw-info.svg
This PR adds a Github action for auto-generation of `tw CLI` screenshots in the USAGE docs.
See the usage example on https://github.com/seqeralabs/nf-core-tower-azure-poc#using-the-tower-cli
> Add the github action for the screenshot

- conf/reflect-config.json
- src/main/java/io/seqera/tower/cli/commands/runs/RelaunchCmd.java
- src/test/java/io/seqera/tower/cli/runs/RunsCmdTest.java
- src/test/resources/runcmd/runs/workflow_launch.json
- Uses the endpoint `/workflow/<workflow_id>/launch` to get the launch to relaunch instead of `/launch/<launch_id>`
- Allows to set a run name when relaunching with `tw runs relaunch --name ...`
- Fixes #244
> Fix relaunch command

- USAGE.md
jq to get specific entries within the JSON output.
> added jq to get specific entries within the JSON output.

- conf/resource-config.json
- src/main/java/io/seqera/tower/cli/commands/LaunchCmd.java
> Allow to override CE of a Tower pipeline at tw launch command

- conf/reflect-config.json
- src/main/java/io/seqera/tower/cli/commands/computeenvs/AddCmd.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/add/AddGoogleBatchCmd.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/add/AddGoogleLifeSciencesCmd.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/GoogleBatchPlatform.java
- src/test/java/io/seqera/tower/cli/computeenvs/platforms/GoogleBatchPlatformTest.java
> Add google batch platform

- src/main/java/io/seqera/tower/cli/commands/computeenvs/add/AbstractAddCmd.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/AbstractPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/AzBatchForgePlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/Platform.java
- src/test/java/io/seqera/tower/cli/computeenvs/platforms/AzBatchForgePlatformTest.java
> Add --container-registry-credentials option to Azure platform

- src/main/java/io/seqera/tower/cli/commands/LaunchCmd.java
> Reuse CE pre-run and post-run scripts at launch command

- conf/reflect-config.json
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/AbstractPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/AltairPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/AwsBatchForgePlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/AwsBatchManualPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/AzBatchForgePlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/AzBatchManualPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/EksPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/GkePlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/GoogleBatchPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/GoogleLifeSciencesPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/K8sPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/LsfPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/MoabPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/SlurmPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/UnivaPlatform.java
- src/test/java/io/seqera/tower/cli/computeenvs/platforms/AltairPlatformTest.java
- src/test/java/io/seqera/tower/cli/computeenvs/platforms/AwsBatchForgePlatformTest.java
> Support custom CE environment variables

- build.gradle
- conf/reflect-config.json
- src/main/java/io/seqera/tower/cli/Tower.java
- src/main/java/io/seqera/tower/cli/commands/SecretsCmd.java
- src/main/java/io/seqera/tower/cli/commands/secrets/AbstractSecretsCmd.java
- src/main/java/io/seqera/tower/cli/commands/secrets/AddCmd.java
- src/main/java/io/seqera/tower/cli/commands/secrets/DeleteCmd.java
- src/main/java/io/seqera/tower/cli/commands/secrets/ListCmd.java
- src/main/java/io/seqera/tower/cli/commands/secrets/SecretRefOptions.java
- src/main/java/io/seqera/tower/cli/commands/secrets/UpdateCmd.java
- src/main/java/io/seqera/tower/cli/commands/secrets/ViewCmd.java
- src/main/java/io/seqera/tower/cli/exceptions/SecretNotFoundException.java
- src/main/java/io/seqera/tower/cli/responses/secrets/SecretAdded.java
- src/main/java/io/seqera/tower/cli/responses/secrets/SecretDeleted.java
- src/main/java/io/seqera/tower/cli/responses/secrets/SecretUpdated.java
- src/main/java/io/seqera/tower/cli/responses/secrets/SecretView.java
- src/main/java/io/seqera/tower/cli/responses/secrets/SecretsList.java
- src/test/java/io/seqera/tower/cli/secrets/SecretsCmdTest.java
> Add secrets support

- conf/reflect-config.json
- conf/resource-config.json
- src/main/java/io/seqera/tower/cli/commands/LaunchCmd.java
- src/main/java/io/seqera/tower/cli/commands/pipelines/AddCmd.java
- src/main/java/io/seqera/tower/cli/commands/pipelines/LaunchOptions.java
- src/main/java/io/seqera/tower/cli/commands/pipelines/UpdateCmd.java
- src/main/java/io/seqera/tower/cli/commands/runs/RelaunchCmd.java
- src/main/java/io/seqera/tower/cli/utils/ModelHelper.java
> Allow to add secrets at pipeline view, launch and add commands

- .github/workflows/build.yml
This PR will add apple developer signature steps in CI workflow for mac
> Added apple developer sign in CI

- .github/workflows/build.yml
- jreleaser.yml
This PR will upgrade Github actions to version 4
> Upgrade Github actions  to version 4

- src/main/java/io/seqera/tower/cli/commands/DataLinksCmd.java
- src/main/java/io/seqera/tower/cli/commands/data/links/BrowseCmd.java
- src/main/java/io/seqera/tower/cli/responses/data/DataLinkContentList.java
- src/test/java/io/seqera/tower/cli/data/DataLinksCmdTest.java
> [Data explorer] content listing

- .github/workflows/build.yml
this PR will colve the issue of tw is not bale to run on mac intel
> changes mac-latest to mac-12

- jreleaser.yml
This PR will set the draft to false, to make release publish the binaries automatically
> set draft to false

- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/AbstractPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/AltairPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/AwsBatchForgePlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/AwsBatchManualPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/AzBatchForgePlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/AzBatchManualPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/EksPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/GkePlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/GoogleBatchPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/GoogleLifeSciencesPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/K8sPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/LsfPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/MoabPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/SlurmPlatform.java
- src/main/java/io/seqera/tower/cli/commands/computeenvs/platforms/UnivaPlatform.java
- src/test/java/io/seqera/tower/cli/computeenvs/platforms/AltairPlatformTest.java
- src/test/java/io/seqera/tower/cli/computeenvs/platforms/AwsBatchForgePlatformTest.java
> Support --nextflow-config when adding compute environment
